ci: new release workflow added using git-cliff instead of release it

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,4 +1,4 @@
-name: Release and publish 
+name: Release and publish changelog
 on:
   workflow_dispatch:
     inputs:
@@ -16,18 +16,18 @@ concurrency: ${{ github.workflow }}-${{ github.ref }}
 permissions: {}
 jobs:
   bump-version:
+    if:  github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
     outputs:
       new-tag: ${{ steps.version.outputs.new-tag }}
     steps:
+
       # Create Github App Token
-      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
+      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
         id: app-token
         with:
           # required
-          # Appid from this app: https://evva.ghe.com/apps/p-lehner/evva-bee
-          app-id: "5302"
-          # Private key from vault https://vault.service.consul:8200/ui/vault/secrets/secret/show/infrastructure/services/external/github-enterprise/github-apps/evva-bee
+          client-id: ${{ vars.GLOBAL_APP_EVVA_BEE_APP_ID }}
           private-key: ${{ secrets.GLOBAL_APP_EVVA_BEE_PRIVATE_KEY }}
 
       # Get GitHub App User ID
@@ -36,57 +36,165 @@ jobs:
         run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
-          GH_HOST: evva.ghe.com
+          GH_HOST: github.com
       - run: |
           git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
           git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
 
-      # Copy repo to action runner
       - name: Checkout repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
         with:
-          fetch-depth: 0 # For release-it and auto-changelog to be able to generate the full changelog
+          fetch-depth: 0 # For git-cliff to generate full logs
           fetch-tags: true
           token: ${{ steps.app-token.outputs.token }}
           ref: main
-          # Make sure the value of GITHUB_TOKEN will persist in repo's config for release-it to use it later
-          # In this case it is a short lived app-token, so its ok
-          persist-credentials: true
-      
-      # Install node dependencies (releaseit + autochangelog)
-      - name: Install node dependencies
-        run: npm ci
 
+      # Check required git cliff files present in repo
+      - name: Check required git cliff files in repo
+        run: |
+          if [[ ! -f cliff.toml || ! -f cliff-changelog.toml ]]; then
+            echo "Error: Both cliff.toml and cliff-changelog.toml files must be present in repo root"
+            exit 1
+          fi
+
+      - name: Declare release type
+        env:
+          USER_INPUT_VERSION: "${{ github.event.inputs.input_version }}"
+        run: |
+          if [[ ! -z "$USER_INPUT_VERSION" ]] ; then
+            echo "Type of release:"$USER_INPUT_VERSION" from user ${GITHUB_ACTOR}"
+          else
+            echo "User did not select release type. It will be automatically determined..."
+          fi
       # Get the latest tag info, increment it accordingly, update the package.json file so it is built with new version
       - name: Update version info for build
         id: version
         env:
           VERSION_TYPE: ${{ github.event.inputs.input_version }}
-          BOT_GITHUB_TOKEN:  ${{ steps.app-token.outputs.token }}
-        # Files to be modified are copied to temp location so repo is returned to original state after build is complete
         run: |
-            npx release-it ${{ github.event.inputs.input_version }} --no-git.commit --no-git.tag --no-git.push --no-github.release --ci
+            git-cliff --bump ${{ github.event.inputs.input_version }} --bumped-version > version
             echo "New version will be $(cat version)"
             NEW_TAG=$(cat version)
             echo "new-tag=$NEW_TAG" >> "$GITHUB_OUTPUT"
 
+      - name: Update version in pubspec.yaml and commit changes
+        env:
+            NEW_TAG: ${{ steps.version.outputs.new-tag }}
+        run: |
+            echo '::group:: Preparing files with updated versions'
+            echo "New version will be $NEW_TAG"
+            sed -i "s/version: .*/version: $NEW_TAG/" ${{ github.workspace}}/pubspec.yaml
+            echo '::endgroup::'
+            echo '::group:: Reading pubspec.yaml'
+            cat ${{ github.workspace }}/pubspec.yaml
+            echo '::endgroup::'
+
+      - name: Commit & Push changes
+        uses: iarekylew00t/verified-bot-commit@126a6a11889ab05bcff72ec2403c326cd249b84c # v2.3.0
+        with:
+          ref: main
+          token:  ${{ steps.app-token.outputs.token }}
+          message: "chore: updated version in pubspec.yaml file"
+          files: |
+            oubspec.yaml
 
   publish:
     needs: bump-version
     runs-on: ubuntu-latest
-    environment: pub.dev # is configured in repo settings with secrets
     permissions:
       contents: write
       id-token: write
       attestations: write
     steps:
+
+      - name: Harden Runner
+        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
+        with:
+          egress-policy: audit
+
       # Create Github App Token
-      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
+      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
         id: app-token
         with:
           # required
           # Appid from this app: https://evva.ghe.com/apps/p-lehner/evva-bee
-          app-id: "5302"
+          client-id: ${{ vars.GLOBAL_APP_EVVA_BEE_APP_ID }}
+          private-key: ${{ secrets.GLOBAL_APP_EVVA_BEE_PRIVATE_KEY }}
+
+      # Get GitHub App User ID
+      - name: Get GitHub App User ID
+        id: get-user-id
+        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+          GH_HOST: github.com
+      - run: |
+          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
+          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+
+      - name: Checkout repository
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+        with:
+          fetch-depth: 0 # For git cliff to be able to generate the full changelog
+          fetch-tags: true
+          token: ${{ steps.app-token.outputs.token }}
+          ref: main
+
+
+      - name: Download and install git-cliff binary # git cliff versions https://github.com/orhun/git-cliff/releases
+        env:
+          git_cliff_version: "2.13.1"
+        run: |
+          set +e
+          wget "https://github.com/orhun/git-cliff/releases/download/v${git_cliff_version}/git-cliff-${git_cliff_version}-x86_64-unknown-linux-gnu.tar.gz"
+          tar -xvzf git-cliff-*.tar.gz
+          mv "./git-cliff-${git_cliff_version}/git-cliff" "/usr/local/bin/git-cliff"
+          rm -rf "./git-cliff-${git_cliff_version}" *.tgz
+          command -v git-cliff
+
+      - name: Publish flutter package
+        run: |
+          rm -f *.tgz
+          flutter pub get
+          flutter pub publish --to-archive abrevva_${{ needs.bump-version.outputs.new-tag }}.tgz
+
+      - name: Create Signed Tag via GH CLI and fetch new tag
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+          TAG_NAME: ${{ needs.bump-version.outputs.new-tag }}
+        run: |
+          gh release create "$TAG_NAME" --target $(git rev-parse HEAD) --notes "Generating..." --title "$TAG_NAME" *.tgz
+          git fetch --tags
+
+      - name: Generate release notes and put in Github temporary location
+        env:
+          TAG_NAME: ${{ needs.bump-version.outputs.new-tag }}
+        run: git-cliff -c cliff.toml --current --output ${{ runner.temp }}/RELEASE_NOTES.md
+
+      - name: Create a release on Github with release notes and provenance
+        env:
+          GH_TOKEN: ${{ github.token }}
+          TAG_NAME: ${{ needs.bump-version.outputs.new-tag }}
+        run: |
+          gh release edit "$TAG_NAME" --notes-file "${{ runner.temp }}/RELEASE_NOTES.md" --latest
+
+      - name: Attest
+        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
+        with:
+          subject-path: "${{ github.workspace }}/*.tgz"
+
+  update-changelog:
+    needs: publish
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      # Create Github App Token
+      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
+        id: app-token
+        with:
+          # required
+          client-id: ${{ vars.GLOBAL_APP_EVVA_BEE_APP_ID }}
           # Private key from vault https://vault.service.consul:8200/ui/vault/secrets/secret/show/infrastructure/services/external/github-enterprise/github-apps/evva-bee
           private-key: ${{ secrets.GLOBAL_APP_EVVA_BEE_PRIVATE_KEY }}
 
@@ -96,220 +204,40 @@ jobs:
         run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
-          GH_HOST: evva.ghe.com
+          GH_HOST: github.com
       - run: |
           git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
           git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
 
-      # Copy repo to action runner
       - name: Checkout repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
         with:
-          fetch-depth: 0 # For release-it and auto-changelog to be able to generate the full changelog
+          fetch-depth: 0 # For git-cliff to be able to generate the full changelog
           fetch-tags: true
           token: ${{ steps.app-token.outputs.token }}
           ref: main
-          # Make sure the value of GITHUB_TOKEN will persist in repo's config for release-it to use it later
-          # In this case it is a short lived app-token, so its ok
-          persist-credentials: true
-          ssh-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }} # IS THIS REQUIRED? WAS FROM OLD RELEASE WORKFLOW
-        
-
-      - name: Update version in package.json files for build
-        id: update-version
+          
+      - name: Download and install git-cliff binary # git cliff versions https://github.com/orhun/git-cliff/releases
         env:
-            VERSION_TYPE: ${{ github.event.inputs.input_version }}
-            BOT_GITHUB_TOKEN:  ${{ steps.app-token.outputs.token }}
-            NEW_TAG: ${{ needs.bump-version.outputs.new-tag }}
-                # Files to be modified are copied to temp location so repo is returned to original state after build is complete
+          git_cliff_version: "2.13.1"
         run: |
-            echo '::group:: Preparing files with updated versions'
-            echo "New version will be $NEW_TAG"
-            mkdir -p /tmp/abrevva-flutter
-            cp ${{ github.workspace }}/package.json /tmp/abrevva-flutter/package.json
-            cp ${{ github.workspace }}/package-lock.json /tmp/abrevva-flutter/package-lock.json
+          set +e
+          wget "https://github.com/orhun/git-cliff/releases/download/v${git_cliff_version}/git-cliff-${git_cliff_version}-x86_64-unknown-linux-gnu.tar.gz"
+          tar -xvzf git-cliff-*.tar.gz
+          mv "./git-cliff-${git_cliff_version}/git-cliff" "/usr/local/bin/git-cliff"
+          rm -rf "./git-cliff-${git_cliff_version}" *.tgz
+          command -v git-cliff
 
-            jq --arg version "$NEW_TAG" '.version = $version' ${{ github.workspace }}/package.json > temp.json && mv temp.json ${{ github.workspace }}/package.json
-            jq --arg version "$NEW_TAG" '.version = $version' ${{ github.workspace }}/package-lock.json > temp.json && mv temp.json ${{ github.workspace }}/package-lock.json
-            jq --arg version "$NEW_TAG" '.packages[""].version = $version' ${{ github.workspace }}/package-lock.json > temp.json && mv temp.json ${{ github.workspace }}/package-lock.json
-            echo '::endgroup::'
-            echo '::group:: Reading package.json'
-            cat ${{ github.workspace }}/package.json
-            echo '::endgroup::'
-            echo '::group:: Reading package-lock.json'
-            cat ${{ github.workspace }}/package-lock.json
-            echo '::endgroup::'
- 
-################################################################################# Below is original release flow
-      - name: Debug inputs
+      - name: Generate changelog using git cliff and cliff-changelog config
         run: |
-          echo "Type of release:${{ github.event.inputs.input_version }} from user ${GITHUB_ACTOR}"
+          git-cliff -c cliff-changelog.toml -o CHANGELOG.md
+          cat CHANGELOG.md
 
-      - name: Setup Node.js
-        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
+      - name: Commit & Push changes
+        uses: iarekylew00t/verified-bot-commit@126a6a11889ab05bcff72ec2403c326cd249b84c # v2.3.0
         with:
-          node-version: lts/*
-
-      - name: Setup Flutter SDK
-        uses: flutter-actions/setup-flutter@03a3a60436d95e16d110127785240139a633ce70 # v4.0
-        with:
-          channel: stable
-          version: latest
-          cache: true
-          cache-sdk: true
-          cache-key: flutter-cache
-
-      - name: Update Flutter SDK
-        run: flutter upgrade
-
-      - name: Install dependencies
-        run: flutter pub get
-
-      - name: Cache node_modules
-        id: node-modules
-        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
-        with:
-          path: |
-            node_modules
-            test-app/node_modules
-            .yarn/cache
-          key: node-modules
-
-      - name: Import GPG key
-        id: import-gpg
-        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
-        with:
-          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-
-      - name: GPG user IDs
-        run: |
-          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
-          echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
-          echo "name:        ${{ steps.import-gpg.outputs.name }}"
-          echo "email:       ${{ steps.import-gpg.outputs.email }}"
-
-      - name: git config
-        run: |
-          git config user.name "${{ steps.import-gpg.outputs.name }}"
-          git config user.email "${{ steps.import-gpg.outputs.email }}"
-
-      - name: Git Status
-        run: git status
-
-      - name: Install dependencies
-        run: npm ci
-
-      - uses: flutter-actions/setup-pubdev-credentials@2bee905b7704ff12e0d8366e69253e8429438170 # v1.1
-
-#########################################################################
-
-    # Return repo to original checked out state
-      - name: Remove created files and return to original repo state
-        run: |
-          cp /tmp/abrevva-react-native/package.json ${{ github.workspace }}/package.json 
-          cp /tmp/abrevva-react-native/package-lock.json ${{ github.workspace }}/package-lock.json 
-
-    # Create Github release - use --no-npm.publish so the release it uses git tags instead
-      - name: Run release-it only create release on github
-        env:
-          BOT_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
-        run: |
-          npx release-it ${{ github.event.inputs.input_version }} --ci
-
-
-########################################################################## Below from original release flow
-
-      - name: Attest
-        uses: actions/attest-build-provenance@520d128f165991a6c774bcb264f323e3d70747f4 # v2.2.0
-        with:
-          subject-path: "${{ github.workspace }}/*.tgz"
-
-##############################################################################
-
-# jobs:
-#   release_publish:
-#     runs-on: ubuntu-latest
-#     environment: pub.dev # is configured in repo settings with secrets
-#     permissions:
-#       contents: write
-#       id-token: write
-#       attestations: write
-#     steps:
-#       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-#         with:
-#           fetch-depth: 0
-#           ssh-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
-
-    #   - name: Debug inputs
-    #     run: |
-    #       echo "Type of release:${{ github.event.inputs.input_version }} from user ${GITHUB_ACTOR}"
-
-    #   - name: Setup Node.js
-    #     uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
-    #     with:
-    #       node-version: lts/*
-
-    #   - name: Setup Flutter SDK
-    #     uses: flutter-actions/setup-flutter@03a3a60436d95e16d110127785240139a633ce70 # v4.0
-    #     with:
-    #       channel: stable
-    #       version: latest
-    #       cache: true
-    #       cache-sdk: true
-    #       cache-key: flutter-cache
-
-    #   - name: Update Flutter SDK
-    #     run: flutter upgrade
-
-    #   - name: Install dependencies
-    #     run: flutter pub get
-
-    #   - name: Cache node_modules
-    #     id: node-modules
-    #     uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
-    #     with:
-    #       path: |
-    #         node_modules
-    #         test-app/node_modules
-    #         .yarn/cache
-    #       key: node-modules
-
-    #   - name: Import GPG key
-    #     id: import-gpg
-    #     uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
-    #     with:
-    #       gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-    #       git_user_signingkey: true
-    #       git_commit_gpgsign: true
-
-    #   - name: GPG user IDs
-    #     run: |
-    #       echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
-    #       echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
-    #       echo "name:        ${{ steps.import-gpg.outputs.name }}"
-    #       echo "email:       ${{ steps.import-gpg.outputs.email }}"
-
-    #   - name: git config
-    #     run: |
-    #       git config user.name "${{ steps.import-gpg.outputs.name }}"
-    #       git config user.email "${{ steps.import-gpg.outputs.email }}"
-
-    #   - name: Git Status
-    #     run: git status
-
-    #   - name: Install dependencies
-    #     run: npm ci
-
-    #   - uses: flutter-actions/setup-pubdev-credentials@2bee905b7704ff12e0d8366e69253e8429438170 # v1.1
-
-    #   - name: Run release-it
-    #     run: npx release-it ${{ github.event.inputs.input_version }} --ci
-    #     env:
-    #       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
-
-    #   - name: Attest
-    #     uses: actions/attest-build-provenance@520d128f165991a6c774bcb264f323e3d70747f4 # v2.2.0
-    #     with:
-    #       subject-path: "${{ github.workspace }}/*.tgz"
+          ref: main
+          token:  ${{ steps.app-token.outputs.token }}
+          message: "docs: Updated changelog"
+          files: |
+            CHANGELOG.md
